<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>WinExe</OutputType>
		<TargetFramework>net10.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<BuiltInComInteropSupport>true</BuiltInComInteropSupport>
		<AvaloniaUseCompiledBindingsByDefault>false</AvaloniaUseCompiledBindingsByDefault>
	</PropertyGroup>

	<ItemGroup>
		<AvaloniaResource Include="**/*.xaml" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Avalonia" Version="12.1.1" />
		<PackageReference Include="Avalonia.Desktop" Version="12.1.1" />
		<PackageReference Include="Avalonia.Wayland" Version="12.1.1" />
		<PackageReference Include="Avalonia.Fonts.Inter" Version="12.1.1" />
		<PackageReference Include="SukiUI" Version="7.0.1" />
		<PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.2" />
	</ItemGroup>
</Project>
